<a href="https://colab.research.google.com/github/gabriellandimdonadel/Ciencia_dados_Dprendizagem_Maquina/blob/main/Capitulo2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gabriel Landim | UDF | Sistemas de informação Ciência de Dados

Manipulação de Dados Tabulares com Pandas - Funções Básicas
*  Tipos de Dados com Pandas
*  Renomeando Colunas
*  Selecionando Linhas e Colunas
*  Adicionando e Removendo Colunas
*  Operações Básicas - Consultas
*  Operações Básicas - Ordenação
*  Operações Básicas - Combinando DataFrames
*  Operações Básicas - Salvando DataFrames

Manipulação de Dados Tabulares com Pandas

In [ ]:
import pandas as pd

In [ ]:
cidades = pd.DataFrame(
   [
        ['Paraná', 'Londrina', 575377, 1356.00],
        ['São Paulo', 'São Carlos', 254484, 1508.00],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
        ['Paraná', 'Curitiba', 1963726, 2293.00],
        ['São Paulo', 'Campinas', 1223237, 1710.00]
   ], columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'])

cidades

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

In [ ]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

In [ ]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

      Estado    Cidade  Habitantes  Salário-Médio
3     Paraná  Curitiba     1963726         2293.0
4  São Paulo  Campinas     1223237         1710.0

In [ ]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [ ]:
cidades.info() # Retorna vazio e imprime na tela as informações gerais do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

Index(['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'], dtype='object')

In [ ]:
cidades['Salário-Médio'].describe() # Retorna um objeto DataFrame com as medidas estatísticas para cada coluna

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salário-Médio, dtype: float64

Tipos de dados com Pandas

In [ ]:
cidades.dtypes
cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')
cidades.dtypes

Estado            object
Cidade            object
Habitantes       float64
Salário-Médio    float64
dtype: object

In [ ]:
cidades['Data'] = ['3-8-2021', '3-9-2021', '3-10-2021', '3-11-2021', '3-12-2021']
cidades['Data'] = pd.to_datetime(cidades['Data'], format='%d-%m-%Y') # Dia, Mês, Ano
cidades

           Estado         Cidade  Habitantes  Salário-Médio       Data
0          Paraná       Londrina    575377.0         1356.0 2021-08-03
1       São Paulo     São Carlos    254484.0         1508.0 2021-09-03
2  Santa Catarina  Florianópolis    508826.0         1798.0 2021-10-03
3          Paraná       Curitiba   1963726.0         2293.0 2021-11-03
4       São Paulo       Campinas   1223237.0         1710.0 2021-12-03

In [ ]:
cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y') # Dia, Mês, Ano
cidades # Novo Formato

           Estado         Cidade  Habitantes  Salário-Médio        Data
0          Paraná       Londrina    575377.0         1356.0  03-08-2021
1       São Paulo     São Carlos    254484.0         1508.0  03-09-2021
2  Santa Catarina  Florianópolis    508826.0         1798.0  03-10-2021
3          Paraná       Curitiba   1963726.0         2293.0  03-11-2021
4       São Paulo       Campinas   1223237.0         1710.0  03-12-2021

Renomeando Colunas

In [ ]:
cidades.rename(columns={'Habitantes': 'N Habitantes', 'Data': 'Data - Censo'}, inplace=True)
cidades

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina      575377.0         1356.0   03-08-2021
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021
3          Paraná       Curitiba     1963726.0         2293.0   03-11-2021
4       São Paulo       Campinas     1223237.0         1710.0   03-12-2021

Selecionando Linhas e Colunas

In [ ]:
cidadesHab = cidades[['N Habitantes', 'Salário-Médio']] # Seleciona as duas colunas com os nomes especificados
cidadesHab

   N Habitantes  Salário-Médio
0      575377.0         1356.0
1      254484.0         1508.0
2      508826.0         1798.0
3     1963726.0         2293.0
4     1223237.0         1710.0

In [ ]:
cidades.loc[[1, 2]] # Seleciona as duas linhas com os nomes especificados

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021

In [ ]:
cidades.iloc[1:3] # Seleciona as linhas do dataframe original, referentes ao índice determinado

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis      508826.0         1798.0   03-10-2021

In [ ]:
cidades.iloc[:, 0:2] # Seleciona todas as linhas e as duas primeiras colunas do dataframe original

           Estado         Cidade
0          Paraná       Londrina
1       São Paulo     São Carlos
2  Santa Catarina  Florianópolis
3          Paraná       Curitiba
4       São Paulo       Campinas

In [ ]:
cidades.iloc[1:3, :3] # Seleciona as duas primeiras linhas e as três primeiras colunas

           Estado         Cidade  N Habitantes
1       São Paulo     São Carlos      254484.0
2  Santa Catarina  Florianópolis      508826.0

In [ ]:
cidades.iloc[:, [1, 3, 0, 2]] # Seleciona todas as linhas e as colunas determinadas

          Cidade  N Habitantes          Estado Sigla
0       Londrina      575377.0          Paraná    PR
1     São Carlos      254484.0       São Paulo    SP
2  Florianópolis      508826.0  Santa Catarina    SC
3       Curitiba     1963726.0          Paraná    PR
4       Campinas     1223237.0       São Paulo    SP

Adicionando e Removendo Colunas

In [ ]:
cidades.insert(2, 'Sigla', ['PR', 'SP', 'SC', 'PR', 'SP']) # Adiciona novos dados no índice dois
cidades.insert(2, 'Sigla-Repetida', cidades['Sigla']) # Adiciona uma coluna repetida "Sigla"
cidades

In [ ]:
cidades.pop('Sigla-Repetida')
# ou
cidades = cidades.drop(['Sigla-Repetida'], axis=1)
cidades

Operações Básicas - Consultas

In [ ]:
cidades.query('`Salário-Médio` > 1400.0')

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

In [ ]:
cidades.query('Estado == "São Paulo"')

      Estado      Cidade Sigla  N Habitantes  Salário-Médio Data - Censo
1  São Paulo  São Carlos    SP      254484.0         1508.0   03-09-2021
4  São Paulo    Campinas    SP     1223237.0         1710.0   03-12-2021

In [ ]:
cidades.query('`N Habitantes` > 500000 and `N Habitantes` < 1300000')

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

Operações Básicas - Ordenação

In [ ]:
cidades.sort_values(by='Cidade', inplace=True)
cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021

In [ ]:
cidades.sort_values(by='Salário-Médio', inplace=True)
cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,03-11-2021

Operações Básicas - Combinando DataFrames

In [ ]:
cidades_salarios = pd.DataFrame(
  [
    ['Paraná', 'Londrina', 1356.00],
    ['São Paulo', 'São Carlos', 1508.00],
    ['Santa Catarina', 'Florianópolis', 1798.00],
    ['Paraná', 'Curitiba', 2293.00],
    ['São Paulo', 'Campinas', 1710.00]
  ], columns=['Estado', 'Cidade', 'Salário-Médio'])
cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [ ]:
cidades_pop = pd.DataFrame(
  [
    ['Londrina', 575377],
    ['São Carlos', 254484],
    ['Florianópolis', 508826],
    ['Curitiba', 1963726],
    ['Campinas', 1223237]
  ], columns=['Cidade', 'Habitantes'])
cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [ ]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade")

           Estado         Cidade  Salário-Médio  Habitantes
0          Paraná       Londrina         1356.0      575377
1       São Paulo     São Carlos         1508.0      254484
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Curitiba         2293.0     1963726
4       São Paulo       Campinas         1710.0     1223237

In [ ]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade", how="outer")

           Estado         Cidade  Salário-Médio  Habitantes
0       São Paulo       Campinas         1710.0     1223237
1          Paraná       Curitiba         2293.0     1963726
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Londrina         1356.0      575377
4       São Paulo     São Carlos         1508.0      254484

In [ ]:
cidades_df1 = pd.DataFrame(
  [
    ['Londrina', 575377],
    ['São Carlos', 254484],
    ['Florianópolis', 508826],
  ], columns=['Cidade', 'Habitantes'])
cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [ ]:
cidades_df2 = pd.DataFrame(
  [
    ['Curitiba', 1963726],
    ['Campinas', 1223237]
  ], columns=['Cidade', 'Habitantes'])
cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [ ]:
pd.concat([cidades_df1, cidades_df2], ignore_index=True)

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

Operações Básicas - Salvando DataFrame

In [ ]:
cidades.to_csv("my_df.csv")
cidades.to_html("my_df.html")
cidades.to_json("my_df.json")